output_dir: "results/results_acs"
seed: 10
task: "ACS"
dryrun: False
save_prompts: False
store: True
timeout: 0.0
task_config: 
    path: "data/preprocess/"
    outer_prompt:
        num_answers: 1
        cot: False
    state: "NY"
    given_attrs: ["PUMA", "MAR", "OCCP", "CIT", "SEX"]
    target: "PINCP"
    total_queries: 10000
    creativity: 0.0
    complexity: 0.0
gen_model: 
  name: "gpt-4o-mini"
  provider: "openai"
  args: {}